version: "3.5"



# Docker services
services:
    # lets-haproxy for raspberry pi
    lets-haproxy:
        image: achetronic/lets-haproxy:latest
        container_name: lets-haproxy
        restart: always
        tty: true
        stdin_open: true
        environment:
            ADMIN_MAIL: "me@achetronic.com"
            SKIP_CREATION: "false"
            
            # Environment: staging | production
            ENVIRONMENT: "staging" 
        volumes:
            - ./letsencrypt/log:/var/log/letsencrypt
            - ./letsencrypt:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"